// <auto-generated />
namespace OPIDChecks.DataContexts.OPIDMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Matched : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Matched));
        
        string IMigrationMetadata.Id
        {
            get { return "201907061846381_Matched"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
